database_name         = "postgress"
database_user        = "test"
database_port        = 5432
multi_az             = false
storage_type         = "gp2"
allocated_storage    = 10
storage_encrypted    = true
engine               = "postgres"
engine_version       = "14.9"
instance_class       = "db.t3.medium"
publicly_accessible  = false
apply_immediately    = false
namespace            = "test"
region               = "us-east-1"
db_parameter_group   = "postgres14"
stage                = "poc"
allowed_cidr_blocks  = [ "172.0.0.0/16" ]
rds_id_element        = "test-db"